[package]
name = "learning-rust"
version = "0.1.0"
authors = ["Dimitri van der Vliet <dimitri.van.der.vliet@blockbax.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
